// All UI copy lives here. Voice: plain, friendly, direct (docs/00). Sentence case, digits for
// numbers, no exclamation marks. The site name and domains are placeholders filled in from config:
// {site.name}, {site.short_name}, {site.domain}, {site.homes_domain}. Other values use {name}.
export const en = {
  'landing.title': '{site.name}',
  'landing.tagline': 'Boards, rings and homepages, all under one login.',
  'landing.online': '{count} users online',
  'auth.login': 'Log in',
  'auth.signup': 'Sign up',
  'auth.welcomeBack': 'Welcome back, {handle}. {count} users online.',
  'board.empty': 'No posts yet.',
  'board.publicNotice': 'Posts on this board are public.',
  'email.verify.subject': 'Confirm your email for {site.name}',
  'email.verify.body':
    'Welcome to {site.name}, {handle}.\n\nConfirm your email address to finish setting up your account:\n{link}\n\nThis link works for 24 hours. If you did not sign up, you can ignore this message.',
  'email.reset.subject': 'Reset your {site.name} password',
  'email.reset.body':
    'Someone asked to reset the password for {handle} on {site.name}.\n\nTo choose a new password, open this link:\n{link}\n\nThis link works for 1 hour and can be used once. If this was not you, you can ignore this message; your password has not changed.',
  'email.passwordChanged.subject': 'Your {site.name} password was changed',
  'email.passwordChanged.body':
    'The password for {handle} on {site.name} was just changed, and you were signed out everywhere.\n\nIf this was not you, reset your password now and contact the admins.',
  'oidc.logout.title': 'Sign out of {site.name}',
  'oidc.logout.question': 'Sign out of {site.name} on this browser?',
  'oidc.logout.button': 'Sign out',
  'oidc.logout.done': 'You have signed out.',
  'oidc.error': 'This sign-in request is not valid. Go back to the app and try again.',
  // ---- shell chrome
  'nav.home': 'Home',
  'nav.apps': 'Apps',
  'nav.back': 'Back',
  'nav.skip': 'Skip to content',
  'nav.logout': 'Log out',
  'nav.account': 'Account menu for {handle}',
  'nav.openWindows': 'Open windows',
  'nav.desktop': 'Desktop',
  'app.settings': 'Settings',
  'app.admin': 'Admin console',
  'app.openApp': 'Open {app}',
  'window.label': '{app} window',
  'window.close': 'Close {app}',
  'window.minimize': 'Minimize {app}',
  'window.maximize': 'Maximize {app}',
  'window.restore': 'Restore {app}',
  'window.focus': 'Show {app}',
  // ---- landing
  'landing.invite': 'Sign-ups are by invite. If you have a code, sign up below.',
  'landing.open': 'Sign-ups are open.',
  'landing.closed': 'Sign-ups are not open right now.',
  // ---- fields and common words
  'field.identifier': 'Handle or email',
  'field.password': 'Password',
  'field.currentPassword': 'Current password',
  'field.newPassword': 'New password',
  'field.email': 'Email',
  'field.handle': 'Handle',
  'field.displayName': 'Display name (optional)',
  'field.invite': 'Invite code',
  'field.code': '6-digit code',
  'field.recoveryCode': 'Recovery code',
  'field.bio': 'About you',
  'field.reason': 'Reason',
  'common.loading': 'Loading',
  'common.retry': 'Try again',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.saved': 'Saved.',
  'common.copy': 'Copy',
  'common.copied': 'Copied.',
  'common.continue': 'Continue',
  'common.working': 'Working',
  'common.none': 'None',
  'role.guest': 'Guest',
  'role.user': 'User',
  'role.trusted': 'Trusted',
  'role.admin': 'Admin',
  'status.active': 'Active',
  'status.suspended': 'Suspended',
  'status.deleted': 'Deleted',
  // ---- auth pages
  'auth.login.title': 'Log in',
  'auth.login.submit': 'Log in',
  'auth.login.forgot': 'Forgot your password?',
  'auth.login.needAccount': 'Need an account? Sign up',
  'auth.totp.prompt': 'Enter the 6-digit code from your authenticator app.',
  'auth.totp.useRecovery': 'Use a recovery code instead',
  'auth.totp.useCode': 'Use an authenticator code instead',
  'auth.signup.title': 'Create your account',
  'auth.signup.submit': 'Sign up',
  'auth.signup.haveAccount': 'Already have an account? Log in',
  'auth.signup.handleHint': '2 to 20 letters, digits, _ or -, starting with a letter.',
  'auth.signup.passwordHint': 'At least 10 characters.',
  'auth.signup.inviteHint': 'This site is invite only.',
  'auth.signup.done': 'Account created. Check your email to confirm your address.',
  'auth.signup.closed': 'Sign-ups are not open right now.',
  'auth.verify.working': 'Confirming your email',
  'auth.verify.ok': 'Your email is confirmed. You can log in now.',
  'auth.verify.failed': 'That link has expired or was already used.',
  'auth.verify.missing': 'This link is missing its token. Use the link from your email.',
  'auth.forgot.title': 'Reset your password',
  'auth.forgot.submit': 'Send reset link',
  'auth.forgot.done': 'If that email has an account, a reset link is on its way. It works for 1 hour.',
  'auth.reset.title': 'Choose a new password',
  'auth.reset.submit': 'Change password',
  'auth.reset.done': 'Your password is changed. Log in with the new one.',
  'auth.reset.missing': 'This link is missing its token. Ask for a new one.',
  'auth.backToLogin': 'Back to log in',
  // ---- two-factor setup
  'twofa.title': 'Set up two-factor authentication',
  'twofa.required': 'Admins need two-factor authentication before they can continue.',
  'twofa.scan': 'Scan this code with an authenticator app, or type the key in.',
  'twofa.key': 'Key',
  'twofa.qrAlt': 'QR code for your authenticator app',
  'twofa.enter': 'Enter the 6-digit code it shows',
  'twofa.enable': 'Turn on',
  'twofa.codes.title': 'Save your recovery codes',
  'twofa.codes.body': 'Each code works once if you lose your authenticator. They are shown only now.',
  'twofa.codes.saved': 'I have saved these codes',
  // ---- settings
  'settings.tab.profile': 'Profile',
  'settings.tab.password': 'Password',
  'settings.tab.twofa': 'Two-factor',
  'settings.tab.appearance': 'Appearance',
  'settings.profile.saved': 'Profile saved.',
  'settings.password.changed': 'Password changed. Your other sessions were signed out.',
  'settings.twofa.on': 'Two-factor authentication is on.',
  'settings.twofa.off': 'Two-factor authentication is off.',
  'settings.twofa.codesLeft': '{count} recovery codes left.',
  'settings.twofa.regen': 'Make new recovery codes',
  'settings.twofa.regenHint': 'Enter a current code. The old recovery codes stop working.',
  'settings.appearance.theme': 'Theme',
  'settings.appearance.effects': 'Effects',
  'settings.appearance.saved': 'Theme saved.',
  'settings.effects.scanlines': 'Scanlines',
  'settings.effects.glow': 'Glow',
  'settings.theme.modern': 'Modern',
  'settings.theme.amber': 'Amber screen',
  // ---- admin console
  'admin.tab.users': 'Users',
  'admin.tab.invites': 'Invites',
  'admin.tab.audit': 'Audit log',
  'admin.forbidden': 'Only admins can see this.',
  'admin.users.search': 'Search users',
  'admin.users.roleFilter': 'Role',
  'admin.users.statusFilter': 'Status',
  'admin.users.any': 'Any',
  'admin.users.none': 'No users match.',
  'admin.users.more': 'Show more',
  'admin.col.handle': 'Handle',
  'admin.col.role': 'Role',
  'admin.col.status': 'Status',
  'admin.col.joined': 'Joined',
  'admin.col.lastSeen': 'Last seen',
  'admin.never': 'Never',
  'admin.user.back': 'All users',
  'admin.user.role': 'Change role',
  'admin.user.reasonHint': 'Recorded in the audit log.',
  'admin.user.apply': 'Apply',
  'admin.user.suspend': 'Suspend',
  'admin.user.unsuspend': 'Unsuspend',
  'admin.user.suspendedNote': 'This user is suspended and cannot log in.',
  'admin.user.ops': 'Ops',
  'admin.user.opsNone': 'No ops.',
  'admin.user.grantOp': 'Grant op',
  'admin.user.opScope': 'Scope',
  'admin.user.opId': 'Board ID, ring ID or channel',
  'admin.user.revoke': 'Revoke',
  'admin.user.history': 'History',
  'admin.user.noHistory': 'Nothing recorded yet.',
  'admin.user.invitedBy': 'Invited by {name} with {code}.',
  'admin.user.noInvite': 'No invite recorded.',
  'admin.user.sessions': '{count} active sessions',
  'admin.user.emailOk': 'Email confirmed',
  'admin.user.emailNo': 'Email not confirmed',
  'admin.user.totpOn': 'Two-factor on',
  'admin.user.totpOff': 'Two-factor off',
  'admin.user.ownAccount': 'This is your own account. Ask another admin to change it.',
  'admin.invites.create': 'Create invite',
  'admin.invites.days': 'Valid for (days)',
  'admin.invites.created': 'New invite: {code}',
  'admin.invites.none': 'No invites yet.',
  'admin.invites.state.open': 'Open',
  'admin.invites.state.used': 'Used',
  'admin.invites.state.expired': 'Expired',
  'admin.invites.usedBy': 'Used by {name}',
  'admin.invites.expires': 'Expires {when}',
  'admin.audit.none': 'Nothing recorded yet.',
  'admin.audit.filter': 'Filter by action',
  'admin.audit.filterHint': 'For example user.role_changed, or user.* for all user actions.',
  'admin.audit.by': 'by {actor}',
  'admin.audit.more': 'Show older entries',
  'admin.audit.system': 'the system',
  'admin.audit.cli': 'the server console',
  'app.boards': 'Boards',
  'app.notifications': 'Notifications',
  'notifications.none': 'Nothing new. Replies, mentions and new threads on boards you watch show up here.',
  'notifications.markAll': 'Mark all read',
  'notifications.reply': '{name} replied to you',
  'notifications.mention': '{name} mentioned you',
  'notifications.watch': '{name} started a thread',
  'notifications.in': 'in {board}',
  'notifications.unreadBadge': 'New',
  'notifications.bell': 'Notifications',
  'notifications.bellCount': 'Notifications, {count} unread',
  'notifications.more': 'Show older notifications',
  'boards.list.none': 'There are no boards yet.',
  'boards.list.other': 'Other boards',
  'boards.new': 'New board',
  'boards.search': 'Search',
  'boards.unread': '{count} unread',
  'boards.threads': '{count} threads',
  'boards.replies': '{count} replies',
  'boards.owner': 'Owner: {name}',
  'boards.badge.private': 'Private',
  'boards.badge.members': 'Users only',
  'boards.badge.archived': 'Archived',
  'boards.watch': 'Watch',
  'boards.unwatch': 'Stop watching',
  'boards.markRead': 'Mark all read',
  'boards.settings': 'Board settings',
  'boards.newThread': 'New thread',
  'boards.threadList': 'Threads',
  'boards.noThreads': 'No threads yet.',
  'boards.loginToPost': 'Log in to post.',
  'boards.verifyToPost': 'Confirm your email address to post.',
  'boards.cannotPost': 'You cannot post on this board.',
  'boards.archivedNote': 'This board is archived. It is read-only.',
  'boards.back': 'Back to {name}',
  'boards.backToBoards': 'All boards',
  'boards.by': 'by {name}',
  'boards.reply': 'Reply',
  'boards.replyingTo': 'Replying to {name}',
  'boards.inReplyTo': 'In reply to {name}',
  'boards.delete': 'Delete',
  'boards.deleteConfirm': 'Delete this post? Its text is erased and cannot be recovered.',
  'boards.deleted': 'This post was deleted by its author.',
  'boards.hidden': 'A moderator hid this post.',
  'boards.view.flat': 'Flat',
  'boards.view.threaded': 'Threaded',
  'boards.view.label': 'View',
  'boards.more': 'Show more',
  'boards.nextUnread': 'Next unread thread',
  'boards.noUnread': 'No unread threads.',
  'boards.keys': 'Keys: j and k move, r replies, n goes to the next unread thread.',
  'boards.compose.subject': 'Subject',
  'boards.compose.subjectHint': 'Up to 71 characters.',
  'boards.compose.body': 'Message',
  'boards.compose.preview': 'Preview',
  'boards.compose.edit': 'Keep writing',
  'boards.compose.previewHelp': 'This is how people on a classic terminal will see it, wrapped at 79 columns.',
  'boards.compose.post': 'Post',
  'boards.compose.posting': 'Posting',
  'boards.compose.quote': 'Quote the post',
  'boards.form.title': 'Create a board',
  'boards.form.slug': 'Address',
  'boards.form.slugHint': 'Lowercase letters, digits and hyphens. It cannot be changed later.',
  'boards.form.name': 'Name',
  'boards.form.description': 'Description',
  'boards.form.visibility': 'Who can read it',
  'boards.form.create': 'Create board',
  'boards.vis.public': 'Public: anyone can read, users can post',
  'boards.vis.members': 'Users only: signed-in users can read and post',
  'boards.vis.short.public': 'Public',
  'boards.vis.short.members': 'Users only',
  'boards.vis.short.private': 'Private',
  'boards.vis.private': 'Private: only the people you add',
  'boards.settings.title': 'Settings for {name}',
  'boards.settings.archive': 'Archive this board',
  'boards.settings.archiveHint': 'An archived board is read-only and stops counting toward your limit.',
  'boards.settings.members': 'Members',
  'boards.settings.addMember': 'Add a member by handle',
  'boards.settings.add': 'Add',
  'boards.settings.remove': 'Remove {name}',
  'boards.settings.forbidden': 'Only the owner, its ops and admins can change this board.',
  'boards.removed': 'A moderator removed this post.',
  'boards.locked': 'This thread is locked. Only moderators can reply.',
  'boards.badge.locked': 'Locked',
  'boards.badge.hidden': 'Hidden',
  'boards.report': 'Report',
  'boards.report.title': 'Report this post',
  'boards.report.category': 'What is wrong with it',
  'boards.report.note': 'Anything the moderators should know (optional)',
  'boards.report.send': 'Send report',
  'boards.report.sent': 'Thanks. The moderators of this board have your report.',
  'boards.report.cat.spam': 'Spam',
  'boards.report.cat.abuse': 'Abuse or harassment',
  'boards.report.cat.illegal': 'Illegal content',
  'boards.report.cat.other': 'Something else',
  'boards.mod.label': 'Moderation',
  'boards.mod.hide': 'Hide',
  'boards.mod.unhide': 'Unhide',
  'boards.mod.remove': 'Remove',
  'boards.mod.lock': 'Lock thread',
  'boards.mod.unlock': 'Unlock thread',
  'boards.mod.move': 'Move thread',
  'boards.mod.moveTo': 'Move to',
  'boards.mod.reason': 'Reason',
  'boards.mod.reasonHint': 'Shown in the mod log and kept in the audit log.',
  'boards.mod.confirm': 'Confirm',
  'boards.mod.removeHint': 'Removing erases the text for good. Hide it instead if you might want it back.',
  'boards.mod.done': 'Done.',
  'boards.mod.noBoards': 'You do not run any other board to move it to.',
  'boards.modlog': 'Mod log',
  'boards.modlog.none': 'Nothing has been moderated here.',
  'boards.modlog.entry': '{actor} {action}',
  'boards.modlog.action.hide': 'hid a post',
  'boards.modlog.action.unhide': 'unhid a post',
  'boards.modlog.action.remove': 'removed a post',
  'boards.modlog.action.lock': 'locked a thread',
  'boards.modlog.action.unlock': 'unlocked a thread',
  'boards.modlog.action.move': 'moved a thread',
  'boards.modlog.moved': 'from {from} to {to}',
  'boards.modlog.author': 'post by {name}',
  'boards.modlog.undone': 'Undone',
  'boards.modlog.undo': 'Undo',
  'boards.modlog.why': 'Reason: {reason}',
  'boards.reports': 'Reports',
  'boards.reports.none': 'No reports.',
  'boards.reports.status': 'Show',
  'boards.reports.status.open': 'Open',
  'boards.reports.status.actioned': 'Acted on',
  'boards.reports.status.dismissed': 'Dismissed',
  'boards.reports.status.all': 'All',
  'boards.reports.by': 'Reported by {name} in {board}',
  'boards.reports.others': '{count} other open reports about this post',
  'boards.reports.escalated': 'Waiting over a day',
  'boards.reports.dismiss': 'Dismiss report',
  'boards.reports.dismissed': 'Dismissed',
  'boards.reports.actioned': 'Acted on',
  'boards.reports.resolvedBy': 'by {name}',
  'boards.reports.postGone': 'The post was deleted.',
  'boards.reports.open': 'Open the thread',
  'boards.settings.ops': 'Board ops',
  'boards.settings.opsHint': 'Ops can hide and remove posts, lock and move threads, and handle reports on this board.',
  'boards.settings.addOp': 'Make someone an op (handle)',
  'boards.settings.removeOp': 'Remove {name} as op',
  'boards.settings.noOps': 'No ops yet. You and the admins moderate this board.',
  'admin.tab.moderation': 'Reports',
  'admin.tab.boards': 'Boards',
  'admin.boards.none': 'No boards yet.',
  'admin.boards.col.name': 'Board',
  'admin.boards.col.owner': 'Owner',
  'admin.boards.col.visibility': 'Who can read',
  'admin.boards.col.threads': 'Threads',
  'admin.boards.col.last': 'Last post',
  'admin.boards.hint': 'Private boards are listed only if you are a member.',
  'boards.search.title': 'Search boards',
  'boards.search.label': 'Search for',
  'boards.search.go': 'Search',
  'boards.search.none': 'Nothing found.',
  'boards.search.in': 'in {board}',
  'error.forbidden': 'You cannot do that.',
  'error.notFound': 'That page does not exist.',
  'error.network': 'Could not reach the site. Check your connection and try again.',
  'error.generic': 'Something went wrong. The admins have been notified.',
} as const;

export type StringKey = keyof typeof en;
