// All UI copy lives here. Voice: plain, friendly, direct (docs/00). Sentence case, digits for
// numbers, no exclamation marks. The site name and domains are placeholders filled in from config:
// {site.name}, {site.short_name}, {site.domain}, {site.homes_domain}. Other values use {name}.
export const en = {
  'landing.title': '{site.name}',
  'landing.tagline': 'Boards, rings and homepages, all under one login.',
  'landing.online': '{count} users online',
  'auth.login': 'Log in',
  'auth.signup': 'Sign up',
  'auth.welcomeBack': 'Welcome back, {handle}. {count} users online.',
  'board.empty': 'No posts yet.',
  'board.publicNotice': 'Posts on this board are public.',
  'email.verify.subject': 'Confirm your email for {site.name}',
  'email.verify.body':
    'Welcome to {site.name}, {handle}.\n\nConfirm your email address to finish setting up your account:\n{link}\n\nThis link works for 24 hours. If you did not sign up, you can ignore this message.',
  'email.reset.subject': 'Reset your {site.name} password',
  'email.reset.body':
    'Someone asked to reset the password for {handle} on {site.name}.\n\nTo choose a new password, open this link:\n{link}\n\nThis link works for 1 hour and can be used once. If this was not you, you can ignore this message; your password has not changed.',
  'email.passwordChanged.subject': 'Your {site.name} password was changed',
  'email.passwordChanged.body':
    'The password for {handle} on {site.name} was just changed, and you were signed out everywhere.\n\nIf this was not you, reset your password now and contact the admins.',
  'oidc.logout.title': 'Sign out of {site.name}',
  'oidc.logout.question': 'Sign out of {site.name} on this browser?',
  'oidc.logout.button': 'Sign out',
  'oidc.logout.done': 'You have signed out.',
  'oidc.error': 'This sign-in request is not valid. Go back to the app and try again.',
  // ---- shell chrome
  'nav.home': 'Home',
  'nav.apps': 'Apps',
  'nav.back': 'Back',
  'nav.skip': 'Skip to content',
  'nav.logout': 'Log out',
  'nav.account': 'Account menu for {handle}',
  'nav.openWindows': 'Open windows',
  'nav.desktop': 'Desktop',
  'app.settings': 'Settings',
  'app.admin': 'Admin console',
  'app.openApp': 'Open {app}',
  'window.label': '{app} window',
  'window.close': 'Close {app}',
  'window.minimize': 'Minimize {app}',
  'window.maximize': 'Maximize {app}',
  'window.restore': 'Restore {app}',
  'window.focus': 'Show {app}',
  // ---- landing
  'landing.invite': 'Sign-ups are by invite. If you have a code, sign up below.',
  'landing.open': 'Sign-ups are open.',
  'landing.closed': 'Sign-ups are not open right now.',
  // ---- fields and common words
  'field.identifier': 'Handle or email',
  'field.password': 'Password',
  'field.currentPassword': 'Current password',
  'field.newPassword': 'New password',
  'field.email': 'Email',
  'field.handle': 'Handle',
  'field.displayName': 'Display name (optional)',
  'field.invite': 'Invite code',
  'field.code': '6-digit code',
  'field.recoveryCode': 'Recovery code',
  'field.bio': 'About you',
  'field.reason': 'Reason',
  'common.loading': 'Loading',
  'common.retry': 'Try again',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.saved': 'Saved.',
  'common.copy': 'Copy',
  'common.copied': 'Copied.',
  'common.continue': 'Continue',
  'common.working': 'Working',
  'common.none': 'None',
  'role.guest': 'Guest',
  'role.user': 'User',
  'role.trusted': 'Trusted',
  'role.admin': 'Admin',
  'status.active': 'Active',
  'status.suspended': 'Suspended',
  'status.deleted': 'Deleted',
  // ---- auth pages
  'auth.login.title': 'Log in',
  'auth.login.submit': 'Log in',
  'auth.login.forgot': 'Forgot your password?',
  'auth.login.needAccount': 'Need an account? Sign up',
  'auth.totp.prompt': 'Enter the 6-digit code from your authenticator app.',
  'auth.totp.useRecovery': 'Use a recovery code instead',
  'auth.totp.useCode': 'Use an authenticator code instead',
  'auth.signup.title': 'Create your account',
  'auth.signup.submit': 'Sign up',
  'auth.signup.haveAccount': 'Already have an account? Log in',
  'auth.signup.handleHint': '2 to 20 letters, digits, _ or -, starting with a letter.',
  'auth.signup.passwordHint': 'At least 10 characters.',
  'auth.signup.inviteHint': 'This site is invite only.',
  'auth.signup.done': 'Account created. Check your email to confirm your address.',
  'auth.signup.closed': 'Sign-ups are not open right now.',
  'auth.verify.working': 'Confirming your email',
  'auth.verify.ok': 'Your email is confirmed. You can log in now.',
  'auth.verify.failed': 'That link has expired or was already used.',
  'auth.verify.missing': 'This link is missing its token. Use the link from your email.',
  'auth.forgot.title': 'Reset your password',
  'auth.forgot.submit': 'Send reset link',
  'auth.forgot.done': 'If that email has an account, a reset link is on its way. It works for 1 hour.',
  'auth.reset.title': 'Choose a new password',
  'auth.reset.submit': 'Change password',
  'auth.reset.done': 'Your password is changed. Log in with the new one.',
  'auth.reset.missing': 'This link is missing its token. Ask for a new one.',
  'auth.backToLogin': 'Back to log in',
  // ---- two-factor setup
  'twofa.title': 'Set up two-factor authentication',
  'twofa.required': 'Admins need two-factor authentication before they can continue.',
  'twofa.scan': 'Scan this code with an authenticator app, or type the key in.',
  'twofa.key': 'Key',
  'twofa.qrAlt': 'QR code for your authenticator app',
  'twofa.enter': 'Enter the 6-digit code it shows',
  'twofa.enable': 'Turn on',
  'twofa.codes.title': 'Save your recovery codes',
  'twofa.codes.body': 'Each code works once if you lose your authenticator. They are shown only now.',
  'twofa.codes.saved': 'I have saved these codes',
  // ---- settings
  'settings.tab.profile': 'Profile',
  'settings.tab.password': 'Password',
  'settings.tab.twofa': 'Two-factor',
  'settings.tab.appearance': 'Appearance',
  'settings.profile.saved': 'Profile saved.',
  'settings.password.changed': 'Password changed. Your other sessions were signed out.',
  'settings.twofa.on': 'Two-factor authentication is on.',
  'settings.twofa.off': 'Two-factor authentication is off.',
  'settings.twofa.codesLeft': '{count} recovery codes left.',
  'settings.twofa.regen': 'Make new recovery codes',
  'settings.twofa.regenHint': 'Enter a current code. The old recovery codes stop working.',
  'settings.appearance.theme': 'Theme',
  'settings.appearance.effects': 'Effects',
  'settings.appearance.saved': 'Theme saved.',
  'settings.effects.scanlines': 'Scanlines',
  'settings.effects.glow': 'Glow',
  'settings.theme.modern': 'Modern',
  'settings.theme.amber': 'Amber screen',
  // ---- admin console
  'admin.tab.users': 'Users',
  'admin.tab.invites': 'Invites',
  'admin.tab.audit': 'Audit log',
  'admin.forbidden': 'Only admins can see this.',
  'admin.users.search': 'Search users',
  'admin.users.roleFilter': 'Role',
  'admin.users.statusFilter': 'Status',
  'admin.users.any': 'Any',
  'admin.users.none': 'No users match.',
  'admin.users.more': 'Show more',
  'admin.col.handle': 'Handle',
  'admin.col.role': 'Role',
  'admin.col.status': 'Status',
  'admin.col.joined': 'Joined',
  'admin.col.lastSeen': 'Last seen',
  'admin.never': 'Never',
  'admin.user.back': 'All users',
  'admin.user.role': 'Change role',
  'admin.user.reasonHint': 'Recorded in the audit log.',
  'admin.user.apply': 'Apply',
  'admin.user.suspend': 'Suspend',
  'admin.user.unsuspend': 'Unsuspend',
  'admin.user.suspendedNote': 'This user is suspended and cannot log in.',
  'admin.user.ops': 'Ops',
  'admin.user.opsNone': 'No ops.',
  'admin.user.grantOp': 'Grant op',
  'admin.user.opScope': 'Scope',
  'admin.user.opId': 'Board ID, ring ID or channel',
  'admin.user.revoke': 'Revoke',
  'admin.user.history': 'History',
  'admin.user.noHistory': 'Nothing recorded yet.',
  'admin.user.invitedBy': 'Invited by {name} with {code}.',
  'admin.user.noInvite': 'No invite recorded.',
  'admin.user.sessions': '{count} active sessions',
  'admin.user.emailOk': 'Email confirmed',
  'admin.user.emailNo': 'Email not confirmed',
  'admin.user.totpOn': 'Two-factor on',
  'admin.user.totpOff': 'Two-factor off',
  'admin.user.ownAccount': 'This is your own account. Ask another admin to change it.',
  'admin.invites.create': 'Create invite',
  'admin.invites.days': 'Valid for (days)',
  'admin.invites.created': 'New invite: {code}',
  'admin.invites.none': 'No invites yet.',
  'admin.invites.state.open': 'Open',
  'admin.invites.state.used': 'Used',
  'admin.invites.state.expired': 'Expired',
  'admin.invites.usedBy': 'Used by {name}',
  'admin.invites.expires': 'Expires {when}',
  'admin.audit.none': 'Nothing recorded yet.',
  'admin.audit.filter': 'Filter by action',
  'admin.audit.filterHint': 'For example user.role_changed, or user.* for all user actions.',
  'admin.audit.by': 'by {actor}',
  'admin.audit.more': 'Show older entries',
  'admin.audit.system': 'the system',
  'admin.audit.cli': 'the server console',
  'error.forbidden': 'You cannot do that.',
  'error.notFound': 'That page does not exist.',
  'error.network': 'Could not reach the site. Check your connection and try again.',
  'error.generic': 'Something went wrong. The admins have been notified.',
} as const;

export type StringKey = keyof typeof en;
