// All UI copy lives here. Voice: plain, friendly, direct (docs/00). Sentence case, digits for
// numbers, no exclamation marks. The site name and domains are placeholders filled in from config:
// {site.name}, {site.short_name}, {site.domain}, {site.homes_domain}. Other values use {name}.
export const en = {
  'landing.title': '{site.name}',
  'landing.tagline': 'Boards, rings and homepages, all under one login.',
  'landing.online': '{count} users online',
  'auth.login': 'Log in',
  'auth.signup': 'Sign up',
  'auth.welcomeBack': 'Welcome back, {handle}. {count} users online.',
  'board.empty': 'No posts yet.',
  'board.publicNotice': 'Posts on this board are public.',
  'email.verify.subject': 'Confirm your email for {site.name}',
  'email.verify.body':
    'Welcome to {site.name}, {handle}.\n\nConfirm your email address to finish setting up your account:\n{link}\n\nThis link works for 24 hours. If you did not sign up, you can ignore this message.',
  'account.deletedName': 'Deleted user',
  'email.export.subject': 'Your {site.name} export is ready',
  'email.export.body': 'Hello {handle},\n\nThe export of everything you made on {site.name} is ready. Download it while you are logged in:\n{link}\n\nIt is kept for {days} days and then deleted. If you did not ask for it, change your password.',
  'email.reset.subject': 'Reset your {site.name} password',
  'email.reset.body':
    'Someone asked to reset the password for {handle} on {site.name}.\n\nTo choose a new password, open this link:\n{link}\n\nThis link works for 1 hour and can be used once. If this was not you, you can ignore this message; your password has not changed.',
  'email.passwordChanged.subject': 'Your {site.name} password was changed',
  'email.passwordChanged.body':
    'The password for {handle} on {site.name} was just changed, and you were signed out everywhere.\n\nIf this was not you, reset your password now and contact the admins.',
  'oidc.logout.title': 'Sign out of {site.name}',
  'oidc.logout.question': 'Sign out of {site.name} on this browser?',
  'oidc.logout.button': 'Sign out',
  'oidc.logout.done': 'You have signed out.',
  'oidc.error': 'This sign-in request is not valid. Go back to the app and try again.',
  // ---- shell chrome
  'nav.home': 'Home',
  'nav.apps': 'Apps',
  'nav.back': 'Back',
  'nav.skip': 'Skip to content',
  'nav.logout': 'Log out',
  'nav.account': 'Account menu for {handle}',
  'nav.openWindows': 'Open windows',
  'nav.desktop': 'Desktop',
  'app.settings': 'Settings',
  'app.admin': 'Admin console',
  'app.openApp': 'Open {app}',
  'window.label': '{app} window',
  'window.close': 'Close {app}',
  'window.minimize': 'Minimize {app}',
  'window.maximize': 'Maximize {app}',
  'window.restore': 'Restore {app}',
  'window.focus': 'Show {app}',
  // ---- landing
  'landing.invite': 'Sign-ups are by invite. If you have a code, sign up below.',
  'landing.open': 'Sign-ups are open.',
  'landing.closed': 'Sign-ups are not open right now.',
  // ---- fields and common words
  'field.identifier': 'Handle or email',
  'field.password': 'Password',
  'field.currentPassword': 'Current password',
  'field.newPassword': 'New password',
  'field.email': 'Email',
  'field.handle': 'Handle',
  'field.displayName': 'Display name (optional)',
  'field.invite': 'Invite code',
  'field.code': '6-digit code',
  'field.recoveryCode': 'Recovery code',
  'field.bio': 'About you',
  'field.reason': 'Reason',
  'common.loading': 'Loading',
  'common.retry': 'Try again',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.saved': 'Saved.',
  'common.copy': 'Copy',
  'common.copied': 'Copied.',
  'common.continue': 'Continue',
  'common.working': 'Working',
  'common.none': 'None',
  'role.guest': 'Guest',
  'role.user': 'User',
  'role.trusted': 'Trusted',
  'role.admin': 'Admin',
  'status.active': 'Active',
  'status.suspended': 'Suspended',
  'status.deleted': 'Deleted',
  // ---- auth pages
  'auth.login.title': 'Log in',
  'auth.login.submit': 'Log in',
  'auth.login.forgot': 'Forgot your password?',
  'auth.login.needAccount': 'Need an account? Sign up',
  'auth.totp.prompt': 'Enter the 6-digit code from your authenticator app.',
  'auth.totp.useRecovery': 'Use a recovery code instead',
  'auth.totp.useCode': 'Use an authenticator code instead',
  'auth.signup.title': 'Create your account',
  'auth.signup.submit': 'Sign up',
  'auth.signup.haveAccount': 'Already have an account? Log in',
  'auth.signup.handleHint': '2 to 20 letters, digits, _ or -, starting with a letter.',
  'auth.signup.passwordHint': 'At least 10 characters.',
  'auth.signup.inviteHint': 'This site is invite only.',
  'auth.signup.done': 'Account created. Check your email to confirm your address.',
  'auth.signup.closed': 'Sign-ups are not open right now.',
  'auth.verify.working': 'Confirming your email',
  'auth.verify.ok': 'Your email is confirmed. You can log in now.',
  'auth.verify.failed': 'That link has expired or was already used.',
  'auth.verify.missing': 'This link is missing its token. Use the link from your email.',
  'auth.forgot.title': 'Reset your password',
  'auth.forgot.submit': 'Send reset link',
  'auth.forgot.done': 'If that email has an account, a reset link is on its way. It works for 1 hour.',
  'auth.reset.title': 'Choose a new password',
  'auth.reset.submit': 'Change password',
  'auth.reset.done': 'Your password is changed. Log in with the new one.',
  'auth.reset.missing': 'This link is missing its token. Ask for a new one.',
  'auth.backToLogin': 'Back to log in',
  // ---- two-factor setup
  'twofa.title': 'Set up two-factor authentication',
  'twofa.required': 'Admins need two-factor authentication before they can continue.',
  'twofa.scan': 'Scan this code with an authenticator app, or type the key in.',
  'twofa.key': 'Key',
  'twofa.qrAlt': 'QR code for your authenticator app',
  'twofa.enter': 'Enter the 6-digit code it shows',
  'twofa.enable': 'Turn on',
  'twofa.codes.title': 'Save your recovery codes',
  'twofa.codes.body': 'Each code works once if you lose your authenticator. They are shown only now.',
  'twofa.codes.saved': 'I have saved these codes',
  // ---- settings
  'settings.tab.profile': 'Profile',
  'settings.tab.password': 'Password',
  'settings.tab.twofa': 'Two-factor',
  'settings.tab.appearance': 'Appearance',
  'settings.tab.data': 'Your data',
  'settings.tab.terminal': 'Terminal password',
  'terminal.intro': 'IRC clients and other terminal programs use a separate password, so a leak there does not expose your website account. It is never your website password.',
  'terminal.isSet': 'You set a terminal password {when}.',
  'terminal.notSet': 'You have no terminal password yet. The Chat app works without one.',
  'terminal.currentHint': 'Your website password, to confirm it is you.',
  'terminal.new': 'New terminal password',
  'terminal.newHint': 'At least 10 characters, different from your website password.',
  'terminal.set': 'Set terminal password',
  'terminal.change': 'Change terminal password',
  'terminal.remove': 'Remove it',
  'terminal.saved': 'Terminal password saved.',
  'terminal.removed': 'Terminal password removed.',
  'data.export.title': 'Export everything you made',
  'data.export.intro': 'You get one archive with your homepage files, guestbook, posts, rings and boards, and a signed list of every file. It is kept for 7 days. You can ask once a day.',
  'data.export.password': 'Your password',
  'data.export.passwordHint': 'We ask again so nobody else can take your data from a device you left logged in.',
  'data.export.includeKey': 'Include my private key, locked with this password',
  'data.export.request': 'Ask for an export',
  'data.export.requested': 'Requested. We will email you when it is ready. You can also come back to this page.',
  'data.export.none': 'No exports yet.',
  'data.export.list': 'Your exports',
  'data.export.status.queued': 'Waiting to be built',
  'data.export.status.running': 'Being built',
  'data.export.status.ready': 'Ready',
  'data.export.status.failed': 'Failed',
  'data.export.status.expired': 'Expired',
  'data.export.download': 'Download {when}',
  'data.export.expires': 'Kept until {when}',
  'data.export.withKey': 'includes your private key',
  'data.delete.title': 'Delete your account',
  'data.delete.intro': 'This cannot be undone. Your homepage, files, domains and exports are deleted, and your account is emptied. Take an export first if you want to keep what you made.',
  'data.delete.postsLegend': 'What happens to your posts and guestbook entries',
  'data.delete.postsKeep': 'Keep them without my name, so conversations still make sense',
  'data.delete.postsErase': 'Erase them; each becomes a note that it was deleted',
  'data.delete.ringsNote': 'If you run a ring, hand it to someone or archive it first.',
  'data.delete.handle': 'Type your handle to confirm',
  'data.delete.password': 'Your password',
  'data.delete.code': 'Current 6-digit code (or a recovery code)',
  'data.delete.go': 'Delete my account for good',
  'data.delete.confirm': 'Delete your account now? This cannot be undone.',
  'admin.user.delete': 'Delete account',
  'admin.user.deleteHint': 'For a request to delete an account. This cannot be undone. The same rules apply as when the person deletes it themselves.',
  'admin.user.deleteGo': 'Delete this account',
  'settings.profile.saved': 'Profile saved.',
  'settings.password.changed': 'Password changed. Your other sessions were signed out.',
  'settings.twofa.on': 'Two-factor authentication is on.',
  'settings.twofa.off': 'Two-factor authentication is off.',
  'settings.twofa.codesLeft': '{count} recovery codes left.',
  'settings.twofa.regen': 'Make new recovery codes',
  'settings.twofa.regenHint': 'Enter a current code. The old recovery codes stop working.',
  'settings.appearance.theme': 'Theme',
  'settings.appearance.effects': 'Effects',
  'settings.appearance.saved': 'Theme saved.',
  'settings.effects.scanlines': 'Scanlines',
  'settings.effects.glow': 'Glow',
  'settings.theme.modern': 'Modern',
  'settings.theme.amber': 'Amber screen',
  // ---- admin console
  'admin.tab.users': 'Users',
  'admin.tab.invites': 'Invites',
  'admin.tab.audit': 'Audit log',
  'admin.forbidden': 'Only admins can see this.',
  'admin.users.search': 'Search users',
  'admin.users.roleFilter': 'Role',
  'admin.users.statusFilter': 'Status',
  'admin.users.any': 'Any',
  'admin.users.none': 'No users match.',
  'admin.users.more': 'Show more',
  'admin.col.handle': 'Handle',
  'admin.col.role': 'Role',
  'admin.col.status': 'Status',
  'admin.col.joined': 'Joined',
  'admin.col.lastSeen': 'Last seen',
  'admin.never': 'Never',
  'admin.user.back': 'All users',
  'admin.user.role': 'Change role',
  'admin.user.rename': 'Change handle',
  'admin.user.renameNew': 'New handle',
  'admin.user.renameHint': 'Their homepage address changes with it, and the old address redirects for 90 days. Nobody else can take the old handle in that time.',
  'admin.user.reasonHint': 'Recorded in the audit log.',
  'admin.user.apply': 'Apply',
  'admin.user.suspend': 'Suspend',
  'admin.user.unsuspend': 'Unsuspend',
  'admin.user.suspendedNote': 'This user is suspended and cannot log in.',
  'admin.user.ops': 'Ops',
  'admin.user.opsNone': 'No ops.',
  'admin.user.grantOp': 'Grant op',
  'admin.user.opScope': 'Scope',
  'admin.user.opId': 'Board ID, ring ID or channel',
  'admin.user.revoke': 'Revoke',
  'admin.user.history': 'History',
  'admin.user.noHistory': 'Nothing recorded yet.',
  'admin.user.invitedBy': 'Invited by {name} with {code}.',
  'admin.user.noInvite': 'No invite recorded.',
  'admin.user.sessions': '{count} active sessions',
  'admin.user.emailOk': 'Email confirmed',
  'admin.user.emailNo': 'Email not confirmed',
  'admin.user.totpOn': 'Two-factor on',
  'admin.user.totpOff': 'Two-factor off',
  'admin.user.ownAccount': 'This is your own account. Ask another admin to change it.',
  'admin.invites.create': 'Create invite',
  'admin.invites.days': 'Valid for (days)',
  'admin.invites.created': 'New invite: {code}',
  'admin.invites.none': 'No invites yet.',
  'admin.invites.state.open': 'Open',
  'admin.invites.state.used': 'Used',
  'admin.invites.state.expired': 'Expired',
  'admin.invites.usedBy': 'Used by {name}',
  'admin.invites.expires': 'Expires {when}',
  'admin.audit.none': 'Nothing recorded yet.',
  'admin.audit.filter': 'Filter by action',
  'admin.audit.filterHint': 'For example user.role_changed, or user.* for all user actions.',
  'admin.audit.by': 'by {actor}',
  'admin.audit.more': 'Show older entries',
  'admin.audit.system': 'the system',
  'admin.audit.cli': 'the server console',
  'homes.report': 'Report this page',
  'homes.notFound': 'There is no homepage here.',
  'homes.notFoundHint': 'The address may be misspelled, or the person may have moved or removed their page.',
  'homes.hidden': 'This homepage is not available.',
  'app.studio': 'Homepage studio',
  'studio.tab.files': 'Files',
  'studio.tab.assets': 'Asset library',
  'studio.tab.settings': 'Settings',
  'studio.view': 'View my homepage',
  'studio.usage': '{used} of {quota} used',
  'studio.usageLabel': 'Space used',
  'studio.updated': 'Last changed {when}',
  'studio.never': 'Not published yet',
  'studio.start.title': 'Start with a template',
  'studio.start.hint': 'Pick one and your page is live straight away. You can change every word and file afterwards.',
  'studio.start.use': 'Use {name}',
  'studio.replaceConfirm': 'This replaces your front page and style file. Your other files stay. Continue?',
  'studio.files.none': 'No files yet.',
  'studio.files.new': 'New file',
  'studio.files.newFolder': 'New folder',
  'studio.files.upload': 'Upload files',
  'studio.files.drop': 'Drop files here to upload them to {folder}.',
  'studio.files.root': 'the top folder',
  'studio.files.name': 'Name',
  'studio.files.nameHint': 'Letters, digits and _ . ~ ( ) + - only, no spaces. For example about.html or img/cat.gif.',
  'studio.files.create': 'Create',
  'studio.files.edit': 'Edit',
  'studio.files.open': 'Open',
  'studio.files.rename': 'Rename or move',
  'studio.files.renameTo': 'New name',
  'studio.files.delete': 'Delete',
  'studio.files.deleteConfirm': 'Delete {name}? This cannot be undone.',
  'studio.files.folderDeleteConfirm': 'Delete the folder {name} and everything in it? This cannot be undone.',
  'studio.files.uploading': 'Uploading {name}',
  'studio.files.uploaded': 'Uploaded {count} files.',
  'studio.files.size': '{size}',
  'studio.edit.title': 'Editing {name}',
  'studio.edit.save': 'Save',
  'studio.edit.saved': 'Saved. The preview is up to date.',
  'studio.edit.unsaved': 'You have changes that are not saved.',
  'studio.edit.close': 'Close editor',
  'studio.edit.preview': 'Preview of {name}',
  'studio.edit.editor': 'Editor for {name}',
  'studio.edit.leave': 'Close without saving your changes?',
  'studio.assets.hint': 'A few dividers, buttons, backgrounds and signs to start with. Adding one puts your own copy in the assets folder.',
  'studio.assets.add': 'Add {name} to my files',
  'studio.assets.added': 'Added. Use it with: {snippet}',
  'studio.settings.title': 'Page title',
  'studio.settings.description': 'Short description',
  'studio.settings.descriptionHint': 'Shown in the homepage directory.',
  'studio.settings.saved': 'Saved.',
  'widgets.guestbook.title': 'Guestbook',
  'widgets.guestbook.none': 'No entries yet. Be the first to sign.',
  'widgets.guestbook.name': 'Your name',
  'widgets.guestbook.url': 'Your web address (optional)',
  'widgets.guestbook.message': 'Your message',
  'widgets.guestbook.sign': 'Sign the guestbook',
  'widgets.guestbook.thanks': 'Thanks for signing.',
  'widgets.guestbook.pending': 'Thanks. The owner will read your message before it shows up.',
  'widgets.guestbook.closed': 'This guestbook is closed.',
  'widgets.guestbook.error': 'That did not work. Try again in a moment.',
  'widgets.counter.label': 'Visitors: {count}',
  'widgets.updated.label': 'Last updated {date}',
  'widgets.updated.never': 'Not updated yet',
  'widgets.online.yes': 'Online now',
  'widgets.online.no': 'Offline',
  'app.homepages': 'Homepages',
  'homepages.title': 'Homepages',
  'homepages.search': 'Search homepages',
  'homepages.random': 'Take me to a random page',
  'homepages.sort': 'Sort by',
  'homepages.sort.recent': 'Recently updated',
  'homepages.sort.name': 'Name',
  'homepages.none': 'No homepages match.',
  'homepages.visit': 'Visit {name}',
  'homepages.by': 'by {name}',
  'homepages.updated': 'Updated {when}',
  'homepages.guestbook': 'Guestbook',
  'homepages.untitled': 'Untitled page',
  'homepages.more': 'Show more',
  'guestbook.title': 'Guestbook of {name}',
  'guestbook.back': 'Back to the homepages',
  'guestbook.visit': 'Visit their page',
  'guestbook.none': 'No entries yet.',
  'guestbook.closed': 'This guestbook is closed.',
  'guestbook.signAs': 'Signing as {name}',
  'guestbook.name': 'Your name',
  'guestbook.url': 'Your web address (optional)',
  'guestbook.message': 'Your message',
  'guestbook.sign': 'Sign the guestbook',
  'guestbook.thanks': 'Thanks for signing.',
  'guestbook.pending': 'Thanks. The owner will read it before it shows up.',
  'guestbook.report': 'Report',
  'guestbook.reported': 'Thanks. The admins have your report.',
  'guestbook.loginHint': 'Log in to sign with your account, or sign as a guest below.',
  'report.homepage.title': 'Report the homepage of {name}',
  'report.homepage.intro': 'Tell the admins what is wrong with this page. They will look at it.',
  'report.homepage.sent': 'Thanks. The admins have your report.',
  'report.homepage.back': 'Back to the homepages',
  'studio.tab.widgets': 'Widgets',
  'studio.tab.guestbook': 'Guestbook',
  'studio.widgets.hint': 'Paste a line into your page where you want the widget to show up. They work on any page in your files.',
  'studio.widgets.guestbook': 'Guestbook',
  'studio.widgets.counter': 'Visitor counter',
  'studio.widgets.updated': 'Last updated',
  'studio.widgets.online': 'Online now',
  'studio.guestbook.mode': 'Who can sign',
  'studio.guestbook.mode.open': 'Anyone, and it shows straight away',
  'studio.guestbook.mode.approval': 'Anyone, but I approve each entry first',
  'studio.guestbook.mode.off': 'Nobody: the guestbook is closed',
  'studio.guestbook.entries': 'Entries',
  'studio.guestbook.none': 'No entries.',
  'studio.guestbook.approve': 'Approve',
  'studio.guestbook.hide': 'Hide',
  'studio.guestbook.show': 'Show again',
  'studio.guestbook.state.visible': 'Showing',
  'studio.guestbook.state.pending': 'Waiting for you',
  'studio.guestbook.state.hidden': 'Hidden',
  'admin.tab.homepages': 'Homepages',
  'admin.homepages.none': 'No homepages match.',
  'admin.homepages.totals': '{count} homepages, {size} in total, {hidden} hidden.',
  'admin.homepages.search': 'Search by handle or title',
  'admin.homepages.hide': 'Hide',
  'admin.homepages.restore': 'Restore',
  'admin.homepages.hidden': 'Hidden',
  'admin.homepages.col.owner': 'Owner',
  'admin.homepages.col.title': 'Title',
  'admin.homepages.col.size': 'Size',
  'admin.homepages.col.updated': 'Last changed',
  'admin.homepages.col.state': 'State',
  'admin.homepages.hideThis': 'Hide the homepage of {name}',
  'boards.reports.hidePage': 'Hide this page',
  'boards.reports.hideEntry': 'Hide this entry',
  'boards.reports.aboutPage': 'Homepage of {name}',
  'boards.reports.aboutEntry': 'Guestbook entry on the page of {name}',
  'boards.reports.byPlain': 'Reported by {name}',
  'rings.nav.label': 'Web ring: {ring}',
  'rings.nav.ring': '{ring}',
  'rings.nav.prev': 'Previous',
  'rings.nav.next': 'Next',
  'rings.nav.random': 'Random',
  'rings.nav.list': 'All members',
  'rings.nav.notMember': 'This page is not part of {ring} at the moment.',
  'app.rings': 'Rings',
  'rings.title': 'Rings',
  'rings.found': 'Found a ring',
  'rings.search': 'Search rings',
  'rings.tag': 'Tag',
  'rings.tag.any': 'Any',
  'rings.sort': 'Sort by',
  'rings.sort.newest': 'Newest',
  'rings.sort.active': 'Most active this week',
  'rings.sort.name': 'Name',
  'rings.random': 'Random ring',
  'rings.none': 'No rings match.',
  'rings.members': '{count} members',
  'rings.foundedBy': 'Founded by {name}',
  'rings.archived': 'Archived',
  'rings.policy.open': 'Anyone can join',
  'rings.policy.approval': 'Joining needs approval',
  'rings.policy.invite': 'By invitation only',
  'rings.join': 'Join this ring',
  'rings.requestJoin': 'Ask to join',
  'rings.acceptInvite': 'Accept the invitation',
  'rings.leave': 'Leave this ring',
  'rings.pending': 'Your request is waiting for the ring’s ops.',
  'rings.invited': 'You are invited to join this ring.',
  'rings.banned': 'You cannot join this ring.',
  'rings.inviteOnly': 'This ring is by invitation only.',
  'rings.joined': 'You are in this ring.',
  'rings.board': 'Open the ring board',
  'rings.about': 'About',
  'rings.latest': 'Latest on the board',
  'rings.latest.none': 'Nothing has been posted yet.',
  'rings.membersHeading': 'Members',
  'rings.members.page': 'Page',
  'rings.members.noPage': 'No page yet',
  'rings.ops': 'Ops',
  'rings.navbar.title': 'Your nav bar',
  'rings.navbar.hint': 'Paste this into your homepage to show the ring’s bar. The plain links inside it work for visitors without scripts.',
  'rings.navbar.style': 'Style',
  'rings.navbar.style.bar': 'Simple bar',
  'rings.navbar.style.buttons': 'Row of buttons',
  'rings.navbar.style.banner': 'Banner with arrows',
  'rings.manage': 'Manage the ring',
  'rings.manage.waiting': 'Waiting to join',
  'rings.manage.invited': 'Invited',
  'rings.manage.banned': 'Banned',
  'rings.manage.approve': 'Approve {name}',
  'rings.manage.remove': 'Remove {name}',
  'rings.manage.ban': 'Ban {name}',
  'rings.manage.unban': 'Lift the ban on {name}',
  'rings.manage.invite': 'Invite someone (handle)',
  'rings.manage.send': 'Send invitation',
  'rings.manage.up': 'Move {name} earlier in the bar',
  'rings.manage.down': 'Move {name} later in the bar',
  'rings.manage.flag.no_homepage': 'No page yet, so the bar skips them',
  'rings.manage.flag.no_nav_bar': 'The nav bar has not been seen on their page',
  'rings.manage.addOp': 'Make a member an op (handle)',
  'rings.manage.removeOp': 'Remove {name} as op',
  'rings.manage.transfer': 'Hand the ring to another trusted member (handle)',
  'rings.manage.transferConfirm': 'Hand this ring over? You stay an op, but they become the founder.',
  'rings.manage.transferGo': 'Hand over',
  'rings.manage.reason': 'Reason',
  'rings.manage.archive': 'Archive this ring',
  'rings.manage.archiveHint': 'An archived ring and its board are read-only and stop counting toward your limit.',
  'rings.form.title': 'Found a ring',
  'rings.form.slug': 'Address',
  'rings.form.slugHint': 'Up to 24 lowercase letters, digits and hyphens. Its board is called ring-, then this.',
  'rings.form.name': 'Name',
  'rings.form.description': 'Short description',
  'rings.form.about': 'About the ring',
  'rings.form.tags': 'Tags',
  'rings.form.tagsHint': 'Up to 5, separated by commas. For example: music, synths.',
  'rings.form.policy': 'Who can join',
  'rings.form.create': 'Found the ring',
  'rings.form.save': 'Save changes',
  'rings.back': 'All rings',
  'boards.list.ring': 'Ring: {name}',
  'admin.tab.rings': 'Rings',
  'admin.rings.none': 'No rings match.',
  'admin.rings.search': 'Search by name or address',
  'admin.rings.col.name': 'Ring',
  'admin.rings.col.founder': 'Founder',
  'admin.rings.col.members': 'Members',
  'admin.rings.col.state': 'State',
  'admin.rings.hide': 'Hide',
  'admin.rings.restore': 'Restore',
  'admin.rings.hideThis': 'Hide the ring {name}',
  'admin.rings.restoreThis': 'Restore the ring {name}',
  'studio.tab.domains': 'Domains',
  'studio.domains.hint': 'Use your own domain for your homepage. Add it, put two records in its DNS settings, then check. Your homepage keeps working at its usual address too.',
  'studio.domains.add': 'Add a domain',
  'studio.domains.name': 'Domain name',
  'studio.domains.nameHint': 'For example mysite.com or www.mysite.com.',
  'studio.domains.none': 'No domains yet.',
  'studio.domains.verified': 'Verified and live',
  'studio.domains.pending': 'Waiting for DNS',
  'studio.domains.step1': 'Step 1: prove it is yours. Add this TXT record.',
  'studio.domains.step2': 'Step 2: point it here. Add this record.',
  'studio.domains.recordName': 'Name',
  'studio.domains.recordValue': 'Value',
  'studio.domains.recordType': 'Type',
  'studio.domains.check': 'Check now for {name}',
  'studio.domains.remove': 'Remove {name}',
  'studio.domains.removeConfirm': 'Remove {name}? Your homepage stays at its usual address.',
  'studio.domains.live': 'Live at https://{name}/',
  'studio.domains.dnsWait': 'DNS changes can take from a few minutes to a day to spread. You can come back and check again.',
  'announcement.region': 'Announcements',
  'announcement.dismiss': 'Dismiss: {title}',
  'admin.tab.config': 'Settings',
  'admin.tab.announcements': 'Announcements',
  'admin.config.readonly': 'The site name and addresses come from the server’s configuration and are changed when it is deployed: {name}, {domain}, {homes}.',
  'admin.config.current': 'Now: {value}',
  'admin.config.default': 'Configuration file: {value}',
  'admin.config.version': 'Version {version}, changed by {who}',
  'admin.config.untouched': 'Not changed from the configuration file',
  'admin.config.new': 'New value',
  'admin.config.review': 'Review change',
  'admin.config.confirm': 'Make this change',
  'admin.config.cancel': 'Cancel',
  'admin.config.preview': 'This will change {name} from {current} to {next}.',
  'admin.config.affected': '{count} people or pages would be affected: {note}.',
  'admin.config.nobody': 'Nobody is affected right now.',
  'admin.config.risky': 'A change to this setting is shown to you first.',
  'admin.config.useFile': 'Use the file’s value again',
  'admin.config.history': 'History of {name}',
  'admin.config.historyNone': 'No changes yet.',
  'admin.config.historyRow': 'Version {version}: {previous} to {value}',
  'admin.config.rollback': 'Bring back version {version}',
  'admin.config.rolledBack': 'Rolled back to version {version}',
  'admin.config.saved': 'Saved. It is in effect now.',
  'admin.config.showHistory': 'History for {name}',
  'setting.signup.mode': 'Who can sign up',
  'setting.signup.mode.invite': 'People with an invitation',
  'setting.signup.mode.open': 'Anyone',
  'setting.signup.minimum_age': 'Minimum age (0 turns the question off)',
  'setting.limits.trusted_board_quota': 'Boards a trusted user can own',
  'setting.limits.trusted_ring_quota': 'Rings a trusted user can found',
  'setting.limits.homepage_quota_mb.user': 'Homepage space for users (MB)',
  'setting.limits.homepage_quota_mb.trusted': 'Homepage space for trusted users (MB)',
  'setting.homes.max_domains': 'Custom domains per person',
  'setting.moderation.public_modlog': 'Show each board’s mod log to everyone who can read the board',
  'admin.ann.new': 'New announcement',
  'admin.ann.title': 'Title',
  'admin.ann.body': 'Message (optional)',
  'admin.ann.level': 'Kind',
  'admin.ann.level.info': 'Notice',
  'admin.ann.level.warning': 'Warning',
  'admin.ann.starts': 'Shows from (empty for now)',
  'admin.ann.ends': 'Stops showing at (empty for no end)',
  'admin.ann.preview': 'How it looks in the shell',
  'admin.ann.publish': 'Publish',
  'admin.ann.none': 'No announcements yet.',
  'admin.ann.end': 'End {title} now',
  'admin.ann.state.live': 'Showing now',
  'admin.ann.state.scheduled': 'Scheduled',
  'admin.ann.state.ended': 'Ended',
  'admin.ann.state.archived': 'Ended early',
  'auth.signup.age': 'I am at least {age} years old.',
  'auth.signup.ageError': 'Please confirm your age to sign up.',
  'auth.signup.legalBefore': 'By signing up you agree to the ',
  'auth.signup.legalAnd': ' and the ',
  'legal.terms': 'terms of service',
  'legal.privacy': 'privacy policy',
  'legal.acceptable-use': 'acceptable use',
  'legal.takedown': 'takedown requests',
  'legal.footer': 'Legal',
  'legal.placeholder': 'This page is placeholder text. The people who run this site have not written their real one yet.',
  'legal.updated': 'Version {version}, updated {when}.',
  'legal.takedown.heading': 'Send a request',
  'legal.takedown.kind': 'What kind of request is this?',
  'legal.takedown.kind.copyright': 'Copyright: it uses my work',
  'legal.takedown.kind.illegal': 'It is illegal',
  'legal.takedown.kind.privacy': 'It shares private information',
  'legal.takedown.kind.other': 'Something else',
  'legal.takedown.url': 'Address of the page or post',
  'legal.takedown.description': 'What is wrong with it?',
  'legal.takedown.name': 'Your name',
  'legal.takedown.email': 'Your email',
  'legal.takedown.emailHint': 'We only use it to reply about this request.',
  'legal.takedown.statement': 'I am telling the truth, and I am the owner of the rights or am authorised to act for them.',
  'legal.takedown.send': 'Send request',
  'legal.takedown.sent': 'Thank you. An admin will read your request and reply by email if we need more.',
  'admin.tab.legal': 'Legal',
  'admin.legal.pages': 'Legal pages',
  'admin.legal.placeholderNote': 'Placeholder text. Replace it with pages you have had reviewed.',
  'admin.legal.edit': 'Edit',
  'admin.legal.title': 'Title',
  'admin.legal.body': 'Text',
  'admin.legal.bodyHint': 'Plain text. Start a line with ## for a heading; leave a blank line between paragraphs.',
  'admin.legal.reason': 'Reason for the change',
  'admin.legal.save': 'Save new version',
  'admin.legal.saved': 'Saved as version {version}.',
  'admin.legal.versions': 'Earlier versions',
  'admin.legal.requests': 'Takedown and legal requests',
  'admin.legal.noRequests': 'No requests.',
  'admin.legal.from': '{name} ({email}) wrote on {when}',
  'admin.legal.resolution': 'Note for the record',
  'admin.legal.actioned': 'Acted on it',
  'admin.legal.declined': 'Decline',
  'admin.legal.resolved.actioned': 'Acted on',
  'admin.legal.resolved.declined': 'Declined',
  'admin.legal.resolvedBy': '{who} on {when}: {note}',
  'admin.tab.irc': 'IRC',
  'admin.irc.off': 'IRC is not set up on this site. Set IRC_SECRET for core and run the IRC server (see the operator docs).',
  'admin.irc.title': 'IRC',
  'admin.irc.unreachable': 'The IRC server is not answering.',
  'admin.irc.noBot': 'The site’s bot is not connected, so channel and op changes are waiting.',
  'admin.irc.syncFailures': 'The last sync could not apply {count} change(s). It will try again.',
  'admin.irc.connected': 'Connected now',
  'admin.irc.peak': 'Most at once: {count}',
  'admin.irc.channels': 'Channels',
  'admin.irc.server': 'Server version',
  'admin.irc.since': 'Running since {when}',
  'admin.irc.liveChannels': 'Channels with people in them',
  'admin.irc.noChannels': 'No channels are open.',
  'admin.irc.col.channel': 'Channel',
  'admin.irc.col.people': 'People',
  'admin.irc.col.topic': 'Topic',
  'admin.irc.unregistered': '(not registered)',
  'admin.irc.online': 'Online ({count})',
  'admin.irc.nobody': 'Nobody is connected.',
  'admin.irc.official': 'Add an official channel',
  'admin.irc.channelName': 'Channel name',
  'admin.irc.officialAdd': 'Add channel',
  'admin.irc.officialAdded': '{name} will be registered in a moment.',
  'admin.irc.disconnect': 'Disconnect someone',
  'admin.irc.disconnectHint': 'Ends their IRC sessions now. They can connect again; to keep someone out, suspend their account.',
  'admin.irc.nick': 'Nick',
  'admin.irc.disconnectButton': 'Disconnect',
  'admin.irc.disconnected': '{nick} was disconnected.',
  'admin.irc.bans': 'Address bans',
  'admin.irc.bansHint': 'Keeps an IP address or network off IRC. To ban a person, suspend their account instead.',
  'admin.irc.noBans': 'No address bans.',
  'admin.irc.banTarget': 'IP address or network',
  'admin.irc.banTargetHint': 'For example 192.0.2.4 or 192.0.2.0/24.',
  'admin.irc.banDuration': 'How long',
  'admin.irc.banDurationHint': 'Like 30m, 12h, 7d or 2w. Leave empty for no end.',
  'admin.irc.banAdd': 'Add ban',
  'admin.irc.banRemove': 'Remove ban on this address',
  'admin.irc.banAdded': '{target} is banned.',
  'admin.irc.banRemoved': 'The ban was removed.',
  'admin.ann.irc': 'Also post it in {channel} on IRC when it starts',
  'admin.tab.status': 'Status',
  'admin.tab.backups': 'Backups',
  'admin.status.title': 'How the site is doing',
  'admin.status.refreshed': 'Updated {when}. This page refreshes itself every 15 seconds.',
  'admin.status.allGood': 'Nothing needs attention.',
  'admin.status.attention': 'Needs attention',
  'admin.status.warn.db_slow': 'The database is slow to answer.',
  'admin.status.warn.redis_down': 'Redis is not answering, so live events are stuck.',
  'admin.status.warn.outbox_backlog': 'Events are piling up waiting to be sent.',
  'admin.status.warn.exports_failing': 'Some exports failed in the last day.',
  'admin.status.warn.reports_waiting': 'Some reports have waited more than a day.',
  'admin.status.warn.backup_overdue': 'There has been no good backup for more than a day.',
  'admin.status.warn.restore_test_overdue': 'No restore test has passed for over a month.',
  'admin.status.warn.disk_low': 'A disk is nearly full.',
  'admin.status.tile.users': 'Users',
  'admin.status.tile.usersDetail': '{active} active, {suspended} suspended, {fresh} new in the last day',
  'admin.status.tile.posts': 'Posts in the last day',
  'admin.status.tile.content': 'Boards and rings',
  'admin.status.tile.contentDetail': '{boards} boards, {rings} rings',
  'admin.status.tile.homepages': 'Homepages',
  'admin.status.tile.homepagesDetail': '{size} of files',
  'admin.status.tile.reports': 'Open reports',
  'admin.status.tile.reportsDetail': '{count} waiting more than a day',
  'admin.status.tile.database': 'Database',
  'admin.status.tile.databaseDetail': 'Answers in {ms} ms',
  'admin.status.tile.redis': 'Redis',
  'admin.status.tile.redisOk': 'Answers in {ms} ms',
  'admin.status.tile.redisDown': 'Not answering',
  'admin.status.tile.redisOff': 'Not set up',
  'admin.status.tile.events': 'Event queue',
  'admin.status.tile.eventsDetail': 'Oldest waiting {age}',
  'admin.status.tile.eventsEmpty': 'Nothing waiting',
  'admin.status.tile.exports': 'Exports',
  'admin.status.tile.exportsDetail': '{queued} waiting, {running} running, {failed} failed in the last day',
  'admin.status.tile.disk': 'Free disk space',
  'admin.status.tile.diskDetail': 'Homepages {homes}, exports {exports}',
  'admin.status.tile.backup': 'Last backup',
  'admin.status.tile.backupNever': 'None recorded',
  'admin.status.tile.restore': 'Last restore test',
  'admin.status.tile.restoreOk': 'Passed {when}',
  'admin.status.tile.restoreFailed': 'Failed {when}',
  'admin.status.tile.restoreNever': 'None recorded',
  'admin.status.chart.posts': 'Posts per hour, last 48 hours: {total} in all',
  'admin.status.chart.signups': 'Sign-ups per hour, last 48 hours: {total} in all',
  'admin.status.chart.heading.posts': 'Posts',
  'admin.status.chart.heading.signups': 'Sign-ups',
  'admin.backups.title': 'Backups and restore tests',
  'admin.backups.intro': 'Backups are made by the operator on the server. A backup only counts once a restore test has brought it back into a scratch database and matched what it holds.',
  'admin.backups.commands': 'Run on the server: cli backup --dir /backups (nightly) and cli restore-test --dir /backups (monthly). Keep the copies somewhere else too, and keep APP_SECRET_KEY and BACKUP_KEY apart from them.',
  'admin.backups.none': 'Nothing has been recorded yet.',
  'admin.backups.kind.backup': 'Backup',
  'admin.backups.kind.restore_test': 'Restore test',
  'admin.backups.status.ok': 'Passed',
  'admin.backups.status.failed': 'Failed',
  'admin.backups.status.running': 'Running',
  'admin.backups.checks': 'What was checked',
  'admin.backups.check.ok': 'ok',
  'admin.backups.check.failed': 'failed',
  'admin.backups.col.kind': 'What',
  'admin.backups.col.status': 'Result',
  'admin.backups.col.when': 'Started',
  'admin.backups.col.size': 'Size',
  'admin.backups.col.detail': 'Detail',
  'app.boards': 'Boards',
  'app.chat': 'Chat',
  'chat.connecting': 'Connecting to chat…',
  'chat.failed': 'Chat could not start. Try again in a minute.',
  'chat.closed': 'You are not connected to chat.',
  'chat.reconnect': 'Connect again',
  'chat.channels': 'Channels',
  'chat.server': 'Server messages',
  'chat.unread': '{count} new',
  'chat.mention': '{count} new, mentions you',
  'chat.people': '{count} here',
  'chat.prefix.owner': 'owner',
  'chat.prefix.admin': 'admin',
  'chat.prefix.op': 'op',
  'chat.prefix.halfop': 'half-op',
  'chat.prefix.voice': 'voice',
  'chat.mute': 'Mute',
  'chat.unmute': 'Unmute',
  'chat.leave': 'Leave',
  'chat.close': 'Close',
  'chat.messages': 'Messages in {name}',
  'chat.messageTo': 'Message {name}',
  'chat.command': 'Type a command, like /join #help',
  'chat.send': 'Send',
  'chat.join': 'Join a channel',
  'chat.joinButton': 'Join',
  'chat.siteChannels': 'Channels on the site',
  'chat.kind.official': 'official',
  'chat.kind.ring': 'the {name} ring',
  'chat.kind.user': 'run by {name}',
  'chat.usersHere': '{count} here',
  'chat.nativeTitle': 'Use your own IRC client',
  'chat.native': 'Connect to {host} on port {port} with TLS. Log in with SASL PLAIN using your handle and your terminal password.',
  'chat.nativeSettings': 'Set a terminal password in Settings',
  'chat.event.join': '{nick} joined',
  'chat.event.part': '{nick} left {text}',
  'chat.event.quit': '{nick} quit {text}',
  'chat.event.kick': '{nick} removed {text}',
  'chat.event.nick': '{nick} is now {text}',
  'chat.event.topic': '{nick} set the topic: {text}',
  'chat.note.connected': 'Connected.',
  'chat.note.error': 'Something went wrong.',
  'chat.note.badChannel': 'That is not a channel name.',
  'chat.note.openFirst': 'Open a channel first.',
  'chat.note.msgWho': 'Who to? Type /msg, their nick, then your message.',
  'chat.note.nick': 'On this site your nick is your handle. An admin can change your handle.',
  'chat.note.unknown': 'Unknown command. Try /join, /part, /me, /msg or /topic.',
  'chat.note.pick': 'Pick a channel to talk in.',
  'app.notifications': 'Notifications',
  'notifications.none': 'Nothing new. Replies, mentions and new threads on boards you watch show up here.',
  'notifications.markAll': 'Mark all read',
  'notifications.reply': '{name} replied to you',
  'notifications.mention': '{name} mentioned you',
  'notifications.watch': '{name} started a thread',
  'notifications.in': 'in {board}',
  'notifications.unreadBadge': 'New',
  'notifications.bell': 'Notifications',
  'notifications.bellCount': 'Notifications, {count} unread',
  'notifications.more': 'Show older notifications',
  'boards.list.none': 'There are no boards yet.',
  'boards.list.other': 'Other boards',
  'boards.new': 'New board',
  'boards.search': 'Search',
  'boards.unread': '{count} unread',
  'boards.threads': '{count} threads',
  'boards.replies': '{count} replies',
  'boards.owner': 'Owner: {name}',
  'boards.badge.private': 'Private',
  'boards.badge.members': 'Users only',
  'boards.badge.archived': 'Archived',
  'boards.watch': 'Watch',
  'boards.unwatch': 'Stop watching',
  'boards.markRead': 'Mark all read',
  'boards.settings': 'Board settings',
  'boards.newThread': 'New thread',
  'boards.threadList': 'Threads',
  'boards.noThreads': 'No threads yet.',
  'boards.loginToPost': 'Log in to post.',
  'boards.verifyToPost': 'Confirm your email address to post.',
  'boards.cannotPost': 'You cannot post on this board.',
  'boards.archivedNote': 'This board is archived. It is read-only.',
  'boards.back': 'Back to {name}',
  'boards.backToBoards': 'All boards',
  'boards.by': 'by {name}',
  'boards.reply': 'Reply',
  'boards.replyingTo': 'Replying to {name}',
  'boards.inReplyTo': 'In reply to {name}',
  'boards.delete': 'Delete',
  'boards.deleteConfirm': 'Delete this post? Its text is erased and cannot be recovered.',
  'boards.deleted': 'This post was deleted by its author.',
  'boards.hidden': 'A moderator hid this post.',
  'boards.view.flat': 'Flat',
  'boards.view.threaded': 'Threaded',
  'boards.view.label': 'View',
  'boards.more': 'Show more',
  'boards.nextUnread': 'Next unread thread',
  'boards.noUnread': 'No unread threads.',
  'boards.keys': 'Keys: j and k move, r replies, n goes to the next unread thread.',
  'boards.compose.subject': 'Subject',
  'boards.compose.subjectHint': 'Up to 71 characters.',
  'boards.compose.body': 'Message',
  'boards.compose.preview': 'Preview',
  'boards.compose.edit': 'Keep writing',
  'boards.compose.previewHelp': 'This is how people on a classic terminal will see it, wrapped at 79 columns.',
  'boards.compose.post': 'Post',
  'boards.compose.posting': 'Posting',
  'boards.compose.quote': 'Quote the post',
  'boards.form.title': 'Create a board',
  'boards.form.slug': 'Address',
  'boards.form.slugHint': 'Lowercase letters, digits and hyphens. It cannot be changed later.',
  'boards.form.name': 'Name',
  'boards.form.description': 'Description',
  'boards.form.visibility': 'Who can read it',
  'boards.form.create': 'Create board',
  'boards.vis.public': 'Public: anyone can read, users can post',
  'boards.vis.members': 'Users only: signed-in users can read and post',
  'boards.vis.short.public': 'Public',
  'boards.vis.short.members': 'Users only',
  'boards.vis.short.private': 'Private',
  'boards.vis.private': 'Private: only the people you add',
  'boards.settings.title': 'Settings for {name}',
  'boards.settings.archive': 'Archive this board',
  'boards.settings.archiveHint': 'An archived board is read-only and stops counting toward your limit.',
  'boards.settings.members': 'Members',
  'boards.settings.addMember': 'Add a member by handle',
  'boards.settings.add': 'Add',
  'boards.settings.remove': 'Remove {name}',
  'boards.settings.forbidden': 'Only the owner, its ops and admins can change this board.',
  'boards.removed': 'A moderator removed this post.',
  'boards.locked': 'This thread is locked. Only moderators can reply.',
  'boards.badge.locked': 'Locked',
  'boards.badge.hidden': 'Hidden',
  'boards.report': 'Report',
  'boards.report.title': 'Report this post',
  'boards.report.category': 'What is wrong with it',
  'boards.report.note': 'Anything the moderators should know (optional)',
  'boards.report.send': 'Send report',
  'boards.report.sent': 'Thanks. The moderators of this board have your report.',
  'boards.report.cat.spam': 'Spam',
  'boards.report.cat.abuse': 'Abuse or harassment',
  'boards.report.cat.illegal': 'Illegal content',
  'boards.report.cat.other': 'Something else',
  'boards.mod.label': 'Moderation',
  'boards.mod.hide': 'Hide',
  'boards.mod.unhide': 'Unhide',
  'boards.mod.remove': 'Remove',
  'boards.mod.lock': 'Lock thread',
  'boards.mod.unlock': 'Unlock thread',
  'boards.mod.move': 'Move thread',
  'boards.mod.moveTo': 'Move to',
  'boards.mod.reason': 'Reason',
  'boards.mod.reasonHint': 'Shown in the mod log and kept in the audit log.',
  'boards.mod.confirm': 'Confirm',
  'boards.mod.removeHint': 'Removing erases the text for good. Hide it instead if you might want it back.',
  'boards.mod.done': 'Done.',
  'boards.mod.noBoards': 'You do not run any other board to move it to.',
  'boards.modlog': 'Mod log',
  'boards.modlog.none': 'Nothing has been moderated here.',
  'boards.modlog.entry': '{actor} {action}',
  'boards.modlog.action.hide': 'hid a post',
  'boards.modlog.action.unhide': 'unhid a post',
  'boards.modlog.action.remove': 'removed a post',
  'boards.modlog.action.lock': 'locked a thread',
  'boards.modlog.action.unlock': 'unlocked a thread',
  'boards.modlog.action.move': 'moved a thread',
  'boards.modlog.moved': 'from {from} to {to}',
  'boards.modlog.author': 'post by {name}',
  'boards.modlog.undone': 'Undone',
  'boards.modlog.undo': 'Undo',
  'boards.modlog.why': 'Reason: {reason}',
  'boards.reports': 'Reports',
  'boards.reports.none': 'No reports.',
  'boards.reports.status': 'Show',
  'boards.reports.status.open': 'Open',
  'boards.reports.status.actioned': 'Acted on',
  'boards.reports.status.dismissed': 'Dismissed',
  'boards.reports.status.all': 'All',
  'boards.reports.by': 'Reported by {name} in {board}',
  'boards.reports.others': '{count} other open reports about this post',
  'boards.reports.escalated': 'Waiting over a day',
  'boards.reports.dismiss': 'Dismiss report',
  'boards.reports.dismissed': 'Dismissed',
  'boards.reports.actioned': 'Acted on',
  'boards.reports.resolvedBy': 'by {name}',
  'boards.reports.postGone': 'The post was deleted.',
  'boards.reports.open': 'Open the thread',
  'boards.settings.ops': 'Board ops',
  'boards.settings.opsHint': 'Ops can hide and remove posts, lock and move threads, and handle reports on this board.',
  'boards.settings.addOp': 'Make someone an op (handle)',
  'boards.settings.removeOp': 'Remove {name} as op',
  'boards.settings.noOps': 'No ops yet. You and the admins moderate this board.',
  'admin.tab.moderation': 'Reports',
  'admin.tab.boards': 'Boards',
  'admin.boards.none': 'No boards yet.',
  'admin.boards.col.name': 'Board',
  'admin.boards.col.owner': 'Owner',
  'admin.boards.col.visibility': 'Who can read',
  'admin.boards.col.threads': 'Threads',
  'admin.boards.col.last': 'Last post',
  'admin.boards.hint': 'Private boards are listed only if you are a member.',
  'boards.search.title': 'Search boards',
  'boards.search.label': 'Search for',
  'boards.search.go': 'Search',
  'boards.search.none': 'Nothing found.',
  'boards.search.in': 'in {board}',
  'error.forbidden': 'You cannot do that.',
  'error.notFound': 'That page does not exist.',
  'error.network': 'Could not reach the site. Check your connection and try again.',
  'error.generic': 'Something went wrong. The admins have been notified.',
} as const;

export type StringKey = keyof typeof en;
